version: '3.8'

services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: hyperativadb
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-boot-app:
    build:
      context: .
    container_name: spring-boot-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local